name: Update CDSL Data

on:
  schedule:
    - cron: "0 2 */15 * *"  
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run scrape

      - name: Commit JSON
        run: |
          git config user.name "cdsl-bot"
          git config user.email "bot@github.com"
          git add data/cdsl-data.json
          git commit -m "auto update cdsl data" || echo "no changes"
          git push
