name: Update Market Data

on:
  schedule:
    - cron: "30 3 * * *"
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # ---- CDSL ----
      - name: Run CDSL scraper
        run: npm run scrape

      # ---- NSE ----
      - name: Run NSE Shareholding scraper
        run: npm run scrape:nse

      # ---- Commit ----
      - name: Commit updates
        run: |
          git config user.name "market-data-bot"
          git config user.email "bot@github.com"

          if [[ `git status --porcelain` ]]; then
            git add data/*.json
            git commit -m "auto: market data update"
            git push
          else
            echo "No data changes"
          fi
